title: "Six Seven"
description: "Internet culture, broken down."
author: "Cassian Johnston"
baseurl: ""
url: "https://sixseven.space"
theme: minima

# Enable GitHub Pages remote theme support
plugins:
  - jekyll-feed
  - jekyll-seo-tag
